functions:
  getLatestDeviceReadings:
    handler: src/handlers/readings/getLatestDeviceReadings/index.handler
    name: ${self:service}-${sls:stage}-sensors-getLatestDeviceReadings
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - dynamodb:Query
        Resource: !GetAtt SensorsTable.Arn
    environment:
      SENSORS_TABLE: !Ref SensorsTable
    events:
      - http:
          path: /sensors/{id}/latest
          method: GET
          cors: true
