resources:
  Resources:
    SensorsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${sls:stage}-sensors
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: ErrorStatus
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: ReadingsByError
            KeySchema:
              - AttributeName: ErrorStatus
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        LocalSecondaryIndexes:
          - IndexName: ErrorsByDevice
            KeySchema:
              - AttributeName: PK
                KeyType: HASH
              - AttributeName: ErrorStatus
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

  Outputs:
    SensorsTableName:
      Description: 'Sensors Table Name'
      Value: !Ref SensorsTable
    SensorsTableArn:
      Description: 'Sensors Table Arn'
      Value: !GetAtt SensorsTable.Arn
